name: CML
on: [push]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on AWS EC2
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_KEY  }}
        run: |
          cml runner \
              --single \
              --cloud=aws \
              --cloud-region=us-east-2c \
              --cloud-type=t2.xlarge \
              --cloud-hdd-size=50 \
              --cloud-gpu=k80 \
              --labels=cml-gpu
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-gpu]
    timeout-minutes: 120 # 72h
    container:
      image: docker://pytorch/pytorch
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tar -xzvf data.tar.gz
          pip install -r requirements.txt
          rm ./data/*/.*.jpeg
          python train.py

          # Create CML report
          #cat metrics.txt >> report.md
          #cml publish plot.png --md --title="Confusion Matrix" >> report.md
          #cml send-comment report.md
